//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureType
    {
        public LectureType()
        {
            this.Lecture = new HashSet<Lecture>();
        }
    
        public int Type_ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Lecture> Lecture { get; set; }
    }
}
