//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineStudyEntities : DbContext
    {
        public OnlineStudyEntities()
            : base("name=OnlineStudyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lecture> Lecture { get; set; }
        public virtual DbSet<LectureType> LectureType { get; set; }
        public virtual DbSet<REGISTRATION> REGISTRATION { get; set; }
    }
}
